name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: web/
        remote_path: /var/www/html/
        remote_host: 20.194.39.12
        remote_user: osam17
        remote_key: ${{ secrets.DEPLOY_KEY }}